{
    "_Type": "Action.Type.ApplicationUpdate",
    "ActionResult": {
        "_Name": "AppUpdate"
    },
    "OnFailure": "/MyCustomers/Rules/AppUpdateFailure.js",
    "OnSuccess": "/MyCustomers/Rules/AppUpdateSuccess.js"
}